# Docker image workflow

name: Docker # ================================================================

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
    paths:
      - ".github/actions/call-r/**"
      - ".github/workflows/docker.yml"
      - "docker/latest/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs: # =======================================================================

  # ---------------------------------------------------------------------------
  build-and-push-images: # create and publish Docker images
  # ---------------------------------------------------------------------------

    strategy:
      matrix:
        context: [ ./.github/actions/call-r, ./docker/latest ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Copy any assets required by the Dockerfile
        run: cp assets/Latin-Modern-Roman-fontfacekit.zip ${{ matrix.context }}

      - name: Set an environment variable for the image tag
        id: tag-generator
        run: |
          echo "TAG=$(basename $CONTEXT)" >> $GITHUB_ENV
        env:
          CONTEXT: ${{ matrix.context }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} # was: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
